2022-01-10 17:47:14,089 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - could not translate host name "db" to address: nodename nor servname provided, or not known

2022-01-10 17:47:14,198 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - could not translate host name "db" to address: nodename nor servname provided, or not known

2022-01-10 17:47:14,408 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - could not translate host name "db" to address: nodename nor servname provided, or not known

2022-01-10 17:47:14,817 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - could not translate host name "db" to address: nodename nor servname provided, or not known

2022-01-10 17:47:15,627 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - could not translate host name "db" to address: nodename nor servname provided, or not known

2022-01-10 17:47:17,238 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - could not translate host name "db" to address: nodename nor servname provided, or not known

2022-01-10 18:01:05,928 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "fw"
LINE 8: ...OIN content.person_film_work pfw ON pfw.film_work_id = fw.id
                                                                  ^

2022-01-10 18:02:39,652 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "fw"
LINE 7: ...OIN content.person_film_work pfw ON pfw.film_work_id = fw.id
                                                                  ^

2022-01-10 18:16:33,974 - [ERROR]     - ElasticTransformator - (ElasticTransformator.py).data_transofrm_for_persons(52) - 1 validation error for RecordPersons
films -> 0
  value is not a valid dict (type=type_error.dict)
2022-01-10 18:18:43,114 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - syntax error at or near ")"
LINE 10:             WHERE p.id IN ()
                                    ^

2022-01-10 18:18:43,232 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - syntax error at or near ")"
LINE 10:             WHERE p.id IN ()
                                    ^

2022-01-10 18:18:43,450 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - syntax error at or near ")"
LINE 10:             WHERE p.id IN ()
                                    ^

2022-01-10 18:18:43,881 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - syntax error at or near ")"
LINE 10:             WHERE p.id IN ()
                                    ^

2022-01-10 18:18:44,722 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - syntax error at or near ")"
LINE 10:             WHERE p.id IN ()
                                    ^

2022-01-10 18:18:46,361 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - syntax error at or near ")"
LINE 10:             WHERE p.id IN ()
                                    ^

2022-01-10 18:44:16,656 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

2022-01-10 18:44:16,774 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

2022-01-10 18:44:16,994 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

2022-01-10 18:44:17,421 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

2022-01-10 18:44:18,264 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

2022-01-10 18:44:19,902 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

2022-01-10 18:44:23,142 - [ERROR]     - Utils.backoff - (backoff.py).inner(21) - missing FROM-clause entry for table "p"
LINE 10:             WHERE p.id IN ('3d8d9bf5-0d90-4353-88ba-4ccc5d2c...
                           ^

